name: semantic-drone-segmentation
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11.7
  - pip=23.3.1
  - mlflow=2.17.2
  - pytorch=2.0.1
  - torchvision=0.15.2
  - cudatoolkit=11.8
  - accelerate=0.27.2
  - jupyter=1.0.0
  - loguru=0.7.2
  - pandas=2.1.4
  - scikit-learn=1.2.2
  - scikit-image=0.24.0
  - transformers=4.41.2
  - numpy=1.26.4
  - matplotlib=3.8.0
  - jupytext=1.16.3
  - openpyxl=3.0.10
  - psutil=6.0.0
  - boto3=1.34.148
  - psycopg2-binary=2.9.9
  - pip:
    - mlserver==1.3.5
    - mlserver-mlflow==1.3.5
    - evaluate==0.4.3
    - torchaudio==2.0.1